### ISSUE TITLE
App does not remember the URL of LHC instance

### ISSUE THREAD

**Issue by ludoja** [LiveHelperChat/electron#1]
After closing/reopening the app, it is necessary to input the URL of LHC webpage. In a regular case, users connects to the same URL all tthe time, so default option shoyld be to remeber the URL address.

**Comment by remdex** [comment]
Yes I agree. It's just first attempt I build app just in a few hours :) you are free to improve it :D

**Comment by ludoja** [comment]
I took it as a beta (alfa), just gave you feedback. Unfortunately I do not code, so my possibilities to contribute are limited. Hope that if covid goes away and LHC starts to bring some value to the company, we will at least sponsor something.
