### ISSUE TITLE
Unable to type in chat window on new chats

### ISSUE THREAD

**Issue by Mart-889443** [LiveHelperChat/electron#3]
The when a new chat comes in, the chat text window appears to be disabled, it doesn't turn blue when you click in it and no text can be entered.

![image](https://user-images.githubusercontent.com/74617976/110923140-77f60e00-8318-11eb-8641-4a538b0a0487.png)

If you minimise the application and then restore it the window can then be clicked on and text entered.

![image](https://user-images.githubusercontent.com/74617976/110923206-8c3a0b00-8318-11eb-867f-888175cb6e24.png)

Tried this on two different PCs

Version 1.2.1v on Windows 10 20H2

**Comment by remdex** [comment]
Sorry, but I can't reproduce.
